-- 코드를 입력하세요
# 2:26
SELECT P.PRODUCT_CODE, SUM(P.PRICE*OS.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(P.PRICE*OS.SALES_AMOUNT) DESC, PRODUCT_CODE ASC;