# 
SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (1-(SELECT 0.01 * DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
            WHERE P.CAR_TYPE = C.CAR_TYPE 
            AND P.DURATION_TYPE = '30일 이상')),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
WHERE (C.CAR_TYPE IN ('세단', 'SUV')) 
    AND
    C.CAR_ID NOT IN 
    (SELECT DISTINCT(CAR_ID) 
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') 
     AND
     C.DAILY_FEE * 30 * (1-(SELECT 0.01 * DISCOUNT_RATE 
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
            WHERE P.CAR_TYPE = C.CAR_TYPE 
            AND P.DURATION_TYPE = '30일 이상')) 
    BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC