-- 코드를 입력하세요
# 11:31
SELECT CAR_ID, 
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE, START_DATE)+1) >= 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
;

# SELECT START_DATE, END_DATE, DATEDIFF(END_DATE, START_DATE)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;