-- 코드를 입력하세요
# 8:08
# SELECT OUT.ANIMAL_ID, OUT.NAME
# FROM ANIMAL_INS AS IN RIGHT JOIN ANIMAL_OUTS AS OUT
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
;