-- 코드를 작성해주세요
# 3:30
SELECT COUNT(FN.FISH_NAME) AS FISH_COUNT, FN.FISH_NAME
FROM FISH_INFO AS F INNER JOIN FISH_NAME_INFO AS FN 
ON F.FISH_TYPE=FN.FISH_TYPE
GROUP BY FN.FISH_NAME
ORDER BY FISH_COUNT DESC;