-- 코드를 입력하세요
# 2: 12
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, 
    SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS P INNER JOIN FOOD_ORDER AS O
USING(PRODUCT_ID)
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC
;