-- 코드를 입력하세요
# 11:02
SELECT II.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FH INNER JOIN ICECREAM_INFO AS II USING (FLAVOR)
GROUP BY II.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
;